#!/bin/bash
# postinst script for astroberry-os-sysmod

set -e

if [ "$1" == "configure" ]; then

# Set cloud-init
# Raspberry
if [ -e /boot/firmware/meta-data ]; then
  sed -i "s/instance_id: .*/instance_id: astroberryos-image/g" /boot/firmware/meta-data
# amd64 version starts from a debootstrap made image, so no default files are present
# and need to be created, including the cloud-init config file.
else
  mkdir -p /boot/firmware
  cat <<EOF > /boot/firmware/README
This folder is here for Astroberry compatibility with scripts
made to work on the first platform, the Raspberry Pi.
Leave it as is.
EOF
  cat <<EOF > /boot/firmware/meta-data
dsmode: local
instance_id: astroberryos-image
EOF
cat <<EOF > /etc/cloud/cloud.cfg.d/99-astroberry.cfg
datasource_list: [ NoCloud, None ]
datasource:
  NoCloud:
    seedfrom: file:///boot/firmware

ssh:
  emit_keys_to_console: false
no_ssh_fingerprints: true
ssh_deletekeys: false
ssh_genkeytypes: []
EOF
fi

cat <<EOF > /boot/firmware/user-data
#cloud-config
hostname: astroberry
manage_etc_hosts: true

users:
- name: astroberry
  groups: users,adm,dialout,audio,netdev,video,plugdev,cdrom,games,input,gpio,spi,i2c,render,sudo
  shell: /bin/bash
  lock_passwd: false
  passwd: \$5\$MRvtBeRUfh\$QGv7UN3cnLPJ00paa82TjuwrjqiFvpj/JDgKKd7ikh4
  sudo: ALL=(ALL) NOPASSWD:ALL

ssh_pwauth: true

timezone: Etc/UTC

runcmd:
- localectl set-x11-keymap "us" pc105
- setupcon -k --force || true
- astroberry-os-init
EOF

#cat <<EOF > /boot/firmware/network-config
#network:
#  version: 2
#
#  ethernets:
#    eth0:
#      dhcp4: true
#      optional: true
#
#  wifis:
#    wlan0:
#      dhcp4: no
#      addresses: [10.42.0.1/24]
#      access-points:
#        "astroberry":
#          password: "astroberry"
#          mode: ap
#      regulatory-domain: GB
#EOF

# Set wireless regulatory domain
if [ -e /boot/firmware/cmdline.txt ] && [ -z "$(grep cfg80211.ieee80211_regdom /boot/firmware/cmdline.txt)" ]; then
	sed -i -e "s/\s*cfg80211.ieee80211_regdom=\S*//" -e "s/\(.*\)/\1 cfg80211.ieee80211_regdom=GB/" /boot/firmware/cmdline.txt
fi

# Set reverse proxy / caddy
cat <<EOF > /etc/caddy/Caddyfile
{
	auto_https disable_redirects
}

http://, https:// {
	tls internal
	tls {
		on_demand
	}
        handle /api* {
            reverse_proxy localhost:8624
        }
        handle /websockify* {
            reverse_proxy localhost:8070
        }
        handle /* {
            reverse_proxy localhost:8080
        }
}
EOF

# Set filesharing / samba
cat <<EOF > /etc/samba/smb.conf
[global]
   workgroup = WORKGROUP
   log file = /var/log/samba/log.%m
   max log size = 1000
   logging = file
   panic action = /usr/share/samba/panic-action %d
   server role = standalone server
   obey pam restrictions = yes
   unix password sync = yes
   passwd program = /usr/bin/passwd %u
   passwd chat = *Enter\snew\s*\spassword:* %n\n *Retype\snew\s*\spassword:* %n\n *password\supdated\ssuccessfully* .
   pam password change = yes
   map to guest = bad user
   usershare allow guests = no
   multicast dns register = no

[Shared Files]
   comment = Shared Files
   path = /home/astroberry/Shared
   browseable = yes
   writeable = yes
   read only = no
   create mask = 0644
   directory mask = 0755
   valid users = astroberry
EOF


# Customize login greeter
if [ -e /etc/lightdm/lightdm-gtk-greeter.conf ]; then
  sed -i "s/^#background=.*/background=\/usr\/share\/astroberry-artwork\/backgrounds\/milkyway-galaxy-center-and-its-companions_1920x1080.jpg/g" /etc/lightdm/lightdm-gtk-greeter.conf
  sed -i "s/^#font-name=.*/font-name=Roboto/g" /etc/lightdm/lightdm-gtk-greeter.conf
  echo "default-user-image=/usr/share/astroberry-artwork/icons/astroberry-avatar-500.png" >> /etc/lightdm/lightdm-gtk-greeter.conf
fi

# Fix vnc slow down on headless system: xfwm4 --compositor=off --vblank=off --replace
if [ -e /etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-session.xml ]; then
  sed -i "s/<value type=\"string\" value=\"xfwm4\"\/>/<value type=\"string\" value=\"xfwm4\"\/><value type=\"string\" value=\"--compositor=off\"\/><value type=\"string\" value=\"--vblank=off\"\/>/g" \
    /etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-session.xml
fi

# Customize GTK settings
if [ -e /etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml ]; then
  sed -i "s/<property name=\"ThemeName\" type=\"string\" value=\".*\"\/>/<property name=\"ThemeName\" type=\"string\" value=\"Adwaita-dark\"\/>/g" \
    /etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml
  sed -i "s/<property name=\"FontName\" type=\"string\" value=\".*\"\/>/<property name=\"FontName\" type=\"string\" value=\"Roboto 11\"\/>/g" \
    /etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml
  sed -i "s/<property name=\"MonospaceFontName\" type=\"string\" value=\".*\"\/>/<property name=\"MonospaceFontName\" type=\"string\" value=\"Monospace 11\"\/>/g" \
    /etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml
fi

if [ -e /etc/xdg/xfce4/panel/default.xml ]; then
  # Enable dark mode for panels
  sed -i "s/<property name=\"dark-mode\" type=\"bool\" value=\".*\"\/>/<property name=\"dark-mode\" type=\"bool\" value=\"true\"\/>/g" \
    /etc/xdg/xfce4/panel/default.xml

  # Customize panel 1
  sed -i "s/<property name=\"size\" type=\"uint\" value=\".*\"\/>/<property name=\"size\" type=\"uint\" value=\"38\"\/>/g" \
    /etc/xdg/xfce4/panel/default.xml
  sed -i "s/<property name=\"icon-size\" type=\"uint\" value=\".*\"\/>/<property name=\"icon-size\" type=\"uint\" value=\"0\"\/>/g" \
    /etc/xdg/xfce4/panel/default.xml
fi

# Customize menu layout
cat <<EOF > /etc/xdg/menus/xfce-applications.menu
<!DOCTYPE Menu PUBLIC "-//freedesktop//DTD Menu 1.0//EN"
  "http://www.freedesktop.org/standards/menu-spec/1.0/menu.dtd">

<Menu>
    <Name>Astroberry</Name>

    <DefaultAppDirs/>
    <DefaultDirectoryDirs/>

    <Include>
        <Category>X-Xfce-Toplevel</Category>
    </Include>

    <Exclude>
        <Filename>xfce4-mail-reader.desktop</Filename>
    </Exclude>

    <Layout>
        <Filename>xfce4-run.desktop</Filename>
        <Separator/>
        <Filename>xfce4-terminal-emulator.desktop</Filename>
        <Filename>xfce4-file-manager.desktop</Filename>
        <Filename>xfce4-web-browser.desktop</Filename>
        <Separator/>
        <Menuname>Astronomy</Menuname>
        <Separator/>
        <Merge type="all"/>
        <Separator/>
        <Filename>xfce4-about.desktop</Filename>
        <Filename>xfce4-session-logout.desktop</Filename>
    </Layout>

    <Menu>
        <Name>Astronomy</Name>
        <Directory>xfce-astronomy.directory</Directory>
        <Include>
            <Category>Science</Category>
            <Category>Education</Category>
            <Category>AstroImaging</Category>
            <Filename>com.google.sites.ser-player.desktop</Filename>
        </Include>
    </Menu>

    <Menu>
        <Name>Settings</Name>
        <Directory>xfce-settings.directory</Directory>
        <Include>
            <Category>Settings</Category>
        </Include>

        <Layout>
            <Filename>xfce-settings-manager.desktop</Filename>
            <Separator/>
            <Merge type="all"/>
        </Layout>

        <Menu>
            <Name>Screensavers</Name>
            <Directory>xfce-screensavers.directory</Directory>
            <Include>
                <Category>Screensaver</Category>
            </Include>
        </Menu>
    </Menu>

    <Menu>
        <Name>Accessories</Name>
        <Directory>xfce-accessories.directory</Directory>
        <Include>
            <Or>
                <Category>Accessibility</Category>
                <Category>Core</Category>
                <Category>Legacy</Category>
                <Category>Utility</Category>
            </Or>
        </Include>
        <Exclude>
            <Or>
                <Filename>xfce4-file-manager.desktop</Filename>
                <Filename>xfce4-terminal-emulator.desktop</Filename>
                <Filename>xfce4-about.desktop</Filename>
                <Filename>xfce4-run.desktop</Filename>
            </Or>
        </Exclude>
    </Menu>

    <Menu>
        <Name>System</Name>
        <Directory>xfce-system.directory</Directory>
        <Include>
            <Or>
                <Category>Emulator</Category>
                <Category>System</Category>
            </Or>
        </Include>
        <Exclude>
            <Or>
                <Filename>xfce4-session-logout.desktop</Filename>
            </Or>
        </Exclude>
    </Menu>


    <Menu>
        <Name>Other</Name>
        <Directory>xfce-other.directory</Directory>
        <OnlyUnallocated/>
        <Include>
            <All/>
        </Include>
    </Menu>
    <DefaultMergeDirs/>

</Menu>

EOF

# Install astroberry-manager
if [ ! -e /opt/astroberry-manager ]; then python -m venv /opt/astroberry-manager; fi
/opt/astroberry-manager/bin/pip install --upgrade astroberry_manager@git+https://github.com/astroberry-official/astroberry-manager

# Disable graphical login
update-rc.d lightdm disable

# Enable services
if [ ! -e /etc/systemd/system/multi-user.target.wants/indiwebmanager.service ]; then ln -s /etc/systemd/system/indiwebmanager.service /etc/systemd/system/multi-user.target.wants/; fi
if [ ! -e /etc/systemd/system/multi-user.target.wants/vncserver.service ]; then ln -s /etc/systemd/system/vncserver.service /etc/systemd/system/multi-user.target.wants/; fi
if [ ! -e /etc/systemd/system/multi-user.target.wants/websockify.service ]; then ln -s /etc/systemd/system/websockify.service /etc/systemd/system/multi-user.target.wants/; fi
if [ ! -e /etc/systemd/system/multi-user.target.wants/astroberry-manager.service ]; then ln -s /etc/systemd/system/astroberry-manager.service /etc/systemd/system/multi-user.target.wants/; fi

fi
