#!/bin/bash
# postinst script for astroberry-os-sysmod

if [ "$1" = "configure" ]; then

    # Set wireless regulatory domain
    if [ -e /boot/firmware/cmdline.txt ] && [ -z "$(grep cfg80211.ieee80211_regdom /boot/firmware/cmdline.txt)" ]; then
	sed -i -e "s/\s*cfg80211.ieee80211_regdom=\S*//" -e "s/\(.*\)/\1 cfg80211.ieee80211_regdom=GB/" /boot/firmware/cmdline.txt
    fi

    # Set required permissions if cmake failed
    if [ -e /etc/NetworkManager/system-connections/Hotspot.nmconnection ]; then chmod 600 /etc/NetworkManager/system-connections/Hotspot.nmconnection; fi

    # Set default desktop background
    update-alternatives --install /usr/share/images/desktop-base/desktop-background desktop-background /usr/share/astroberry-artwork/backgrounds/sci-fi-planet-darkness-night_1920x1080_bw.jpg 80

    # Enable services
    if [ ! ischroot ]; then
        if [ ! -e /etc/systemd/system/multi-user.target.wants/astroberry-indiwebmanager.service ]; then ln -s /etc/systemd/system/astroberry-indiwebmanager.service /etc/systemd/system/multi-user.target.wants/; fi
        if [ ! -e /etc/systemd/system/multi-user.target.wants/astroberry-desktop-web.service ]; then ln -s /etc/systemd/system/astroberry-desktop-web.service /etc/systemd/system/multi-user.target.wants/; fi
        if [ ! -e /etc/systemd/system/multi-user.target.wants/astroberry-desktop-vnc.service ]; then ln -s /etc/systemd/system/astroberry-desktop-vnc.service /etc/systemd/system/multi-user.target.wants/; fi
        if [ ! -e /etc/systemd/system/multi-user.target.wants/astroberry-websockify.service ]; then ln -s /etc/systemd/system/astroberry-websockify.service /etc/systemd/system/multi-user.target.wants/; fi
    else
        systemctl enable astroberry-indiwebmanager.service && systemctl start astroberry-indiwebmanager.service
        systemctl enable astroberry-desktop-web.service && systemctl start astroberry-desktop-web.service
        systemctl enable astroberry-desktop-vnc.service && systemctl start astroberry-desktop-vnc.service
        systemctl enable astroberry-websockify.service && systemctl start astroberry-websockify.service
    fi

fi
