#!/bin/bash
# postrm script for astroberry-os-sysmod

# Custom config files for other packages.
# We need to remove the divert when package is removed.
# The original files are renamed to *.distrib when package is installed.
# When the package is removed, the original files are restored.
# /boot/firmware/meta-data
# /boot/firmware/user-data
# /boot/firmware/network-config
# /etc/samba/smb.conf
# /etc/caddy/Caddyfile
# /etc/lightdm/lightdm-gtk-greeter.conf
# /etc/xdg/menus/xfce-applications.menu
# /etc/xdg/xfce4/panel/default.xml
# /etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml
# /etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-session.xml
# /etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml
# /etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then

    # We operate on fat32 so we need to use mv instead of dpkg-divert
    mv /boot/firmware/meta-data.orig.dpkg-distrib /boot/firmware/meta-data || true
    mv /boot/firmware/user-data.orig.dpkg-distrib /boot/firmware/user-data || true
    mv /boot/firmware/network-config.orig.dpkg-distrib /boot/firmware/network-config || true

    dpkg-divert --remove --package astroberry-os-sysmod --rename /etc/samba/smb.conf || true
    dpkg-divert --remove --package astroberry-os-sysmod --rename /etc/caddy/Caddyfile || true
    dpkg-divert --remove --package astroberry-os-sysmod --rename /etc/lightdm/lightdm-gtk-greeter.conf || true
    dpkg-divert --remove --package astroberry-os-sysmod --rename /etc/xdg/menus/xfce-applications.menu || true
    dpkg-divert --remove --package astroberry-os-sysmod --rename /etc/xdg/xfce4/panel/default.xml || true
    dpkg-divert --remove --package astroberry-os-sysmod --rename /etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml || true
    dpkg-divert --remove --package astroberry-os-sysmod --rename /etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-session.xml || true
    dpkg-divert --remove --package astroberry-os-sysmod --rename /etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml || true
    dpkg-divert --remove --package astroberry-os-sysmod --rename /etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml || true

fi
