#!/bin/bash
# preinst script for astroberry-os-sysmod

if [ "$1" = "install" ] || [ "$1" = "upgrade" ]; then

    # Revert changes introduced by legacy astroberry-image-sysmod.sh before v3.2
    # Changes are re-applied by this package from v3.2 onwards.
    [ -f /etc/astroberry/version ] && VERSION=$(cat /etc/astroberry/version)
    if [[ "$VERSION" == "3.0" ]] || [[ "$VERSION" == "3.1" ]]; then

        # Re-enable graphical login manager
        systemctl enable lightdm || true

        # Stop and disable services

        [ -L /etc/systemd/system/multi-user.target.wants/vncserver.service ] && rm /etc/systemd/system/multi-user.target.wants/vncserver.service || true
        [ -e /etc/systemd/system/vncserver.service ] && systemctl stop vncserver && rm /etc/systemd/system/vncserver.service || true

        [ -L /etc/systemd/system/multi-user.target.wants/indiwebmanager.service ] && rm /etc/systemd/system/multi-user.target.wants/indiwebmanager.service || true
        [ -e /etc/systemd/system/indiwebmanager.service ] && systemctl stop indiwebmanager && rm /etc/systemd/system/indiwebmanager.service || true

        [ -L /etc/systemd/system/multi-user.target.wants/websockify.service ] && rm /etc/systemd/system/multi-user.target.wants/websockify.service || true
        [ -e /etc/systemd/system/websockify.service ] && systemctl stop websockify && rm /etc/systemd/system/websockify.service || true

        [ -L /etc/systemd/system/multi-user.target.wants/astroberry-manager.service ] && rm /etc/systemd/system/multi-user.target.wants/astroberry-manager.service || true
        [ -e /etc/systemd/system/astroberry-manager.service ] && systemctl stop astroberry-manager && rm /etc/systemd/system/astroberry-manager.service || true

        # Remove legacy Astroberry Manager files
        [ -d /opt/astroberry-manager ] && rm -rf /opt/astroberry-manager || true

        # Delete legacy config files
        [ -e /etc/polkit-1/rules.d/10-networkmanager.rules ] && rm -rf /etc/polkit-1/rules.d/10-networkmanager.rules || true
        [ -e /etc/polkit-1/rules.d/10-synaptic.rules ] && rm -rf /etc/polkit-1/rules.d/10-synaptic.rules || true
        [ -e /etc/polkit-1/rules.d/10-power-manager.rules ] && rm -rf /etc/polkit-1/rules.d/10-power-manager.rules || true
        [ -e /etc/polkit-1/rules.d/10-file-manager.rules ] && rm -rf /etc/polkit-1/rules.d/10-file-manager.rules || true

        # Restore default configuration files
        [ -e /etc/caddy/Caddyfile.default ] && mv /etc/caddy/Caddyfile.default /etc/caddy/Caddyfile || true
        [ -e /etc/samba/smb.conf.default ] && mv /etc/samba/smb.conf.default /etc/samba/smb.conf || true
        [ -e /etc/xdg/menus/xfce-applications.menu.default ] && mv /etc/xdg/menus/xfce-applications.menu.default /etc/xdg/menus/xfce-applications.menu || true

    fi

fi

#DEBHELPER#
exit 0
