#!/bin/bash
# prerm script for astroberry-os-sysmod

if [ "$1" = "remove" ]; then

    # Restore default desktop background
    update-alternatives --remove desktop-background /usr/share/astroberry-artwork/backgrounds/sci-fi-planet-darkness-night_1920x1080_bw.jpg

    # Stop and disable services
    systemctl stop astroberry-indiwebmanager.service && systemctl disable astroberry-indiwebmanager.service
    systemctl stop astroberry-desktop-web.service && systemctl disable astroberry-desktop-web.service
    systemctl stop astroberry-desktop-vnc.service && systemctl disable astroberry-desktop-vnc.service
    systemctl stop astroberry-websockify.service && systemctl disable astroberry-websockify.service

fi
