#!/bin/bash
# prerm script for astroberry-os-sysmod

if [ "$1" == "remove" -o "$1" == "purge" ]; then
        # Disable Astroberry Manager
        systemctl stop astroberry-manager.service && systemctl disable astroberry-manager.service

	# Remove Astroberry Manager
	if [ -e /opt/astroberry-manager ]; then rm -rf /opt/astroberry-manager; fi

        # Disable INDI Web Manager
        systemctl stop indiwebmanager.service && systemctl disable indiwebmanager.service

        # Disable TigerVNC
        systemctl stop vncserver.service && systemctl disable vncserver.service

        # Disable Websockify
        systemctl stop websockify.service && systemctl disable websockify.service

	# Restore default config files
	if [ -e /boot/firmware/meta-data.default ]; then mv /boot/firmware/meta-data.default /boot/firmware/meta-data; fi
	if [ -e /boot/firmware/user-data.default ]; then mv /boot/firmware/user-data.default /boot/firmware/user-data; fi
	if [ -e /boot/firmware/network-config.default ]; then mv /boot/firmware/network-config.default /boot/firmware/network-config; fi
	if [ -e /etc/caddy/Caddyfile.default ]; then mv /etc/caddy/Caddyfile.default /etc/caddy/Caddyfile; fi
	if [ -e /etc/samba/smb.conf.default ]; then mv /etc/samba/smb.conf.default /etc/samba/smb.conf; fi

fi
