[greeter]
background=/usr/share/astroberry-artwork/backgrounds/milkyway-galaxy-center-and-its-companions_1920x1080.jpg
#user-background=
#theme-name=
#icon-theme-name=
font-name=Roboto
#xft-antialias=
#xft-dpi=
#xft-hintstyle=
#xft-rgba=
#indicators=
#clock-format=
#keyboard=
#reader=
#position=
#screensaver-timeout=
default-user-image=/usr/share/astroberry-artwork/icons/astroberry-avatar-500.png
