#!/bin/bash

set -xe

cleanup() {
    rm -rf /usr/bin/astroberry-os-init
    rm -rf /usr/bin/astroberry-desktop-init
}
trap cleanup EXIT

# Enable radio
nmcli radio wifi on

# Enable file sharing
if [ ! -e /home/astroberry/Shared ]; then su astroberry -c "mkdir -p /home/astroberry/Shared"; fi
echo -ne "astroberry\nastroberry\n" | smbpasswd -a -s astroberry

# Apply default configuration to user desktop
if [ -e /usr/bin/astroberry-desktop-init ]; then
    su astroberry -c "/usr/bin/astroberry-desktop-init" && sleep 1 && systemctl restart vncserver.service
fi

# Trust local CA
caddy trust
