#!/bin/bash

set -xe

UID=1000

while ! pgrep -u astroberry xfsettingsd > /dev/null; do
    sleep 1
done
export DBUS_SESSION_BUS_ADDRESS=\$(grep -z '^DBUS_SESSION_BUS_ADDRESS=' \\
    /proc/\$(pgrep -u astroberry xfsettingsd | head -n 1)/environ \\
    | tr -d '\0' \\
    | cut -d= -f2-)
export DISPLAY=:70

# Window title font
xfconf-query -c xfwm4 -p /general/title_font -n -t string -s "Roboto Bold 11"

# Desktop background
xfconf-query -c xfce4-desktop -n -t string -p /backdrop/screen0/monitorVNC-0/workspace0/last-image \
  -s /usr/share/astroberry-artwork/backgrounds/sci-fi-planet-darkness-night_1920x1080_bw.jpg

# Desktop icons
xfconf-query -c xfce4-desktop -n -t int -p /desktop-icons/style -s 0

# Application menu
xfconf-query -c xfce4-panel -p /plugins/plugin-1/button-icon -n -t string -s /usr/share/astroberry-artwork/icons/astroberry-icon-white.svg
xfconf-query -c xfce4-panel -p /plugins/plugin-1/button-title -n -t string -s "Astroberry OS"
xfconf-query -c xfce4-panel -p /plugins/plugin-1/show-button-title -n -t bool -s true

# Action buttons
xfconf-query -c xfce4-panel -p /plugins/plugin-10/appearance -n -t int -s 0
xfconf-query -c xfce4-panel -p /plugins/plugin-10/items -n -a \
  -t string -s "-lock-screen" -t string -s "-switch-user" -t string -s "-separator" -t string -s "-suspend" -t string -s "-hibernate" -t string -s "-hybrid-sleep" -t string -s "-separator" \
  -t string -s "+shutdown" -t string -s "+restart" -t string -s "+separator" -t string -s "+logout" -t string -s "-logout-dialog"

# Clock
xfconf-query -c xfce4-panel -p /plugins/plugin-8/digital-date-font -n -t string -s "Roboto 11"
xfconf-query -c xfce4-panel -p /plugins/plugin-8/digital-time-font -n -t string -s "Roboto 11"
xfconf-query -c xfce4-panel -p /plugins/plugin-8/digital-time-format -n -t string -s "%T"
